module.exports = function(data) {
  return (function() {
    var __runtime;
    __runtime = require("hamlet-runtime")(this);
    __runtime.push(document.createDocumentFragment());
    __runtime.push(document.createElement("h2"));
    __runtime.text("2. To Do List");
    __runtime.pop();
    __runtime.push(document.createElement("input"));
    __runtime.attribute("type", "text");
    __runtime.attribute("value", this.value);
    __runtime.attribute("placeholder", "What needs to be done?");
    __runtime.attribute("onkeydown", this.add);
    __runtime.pop();
    __runtime.push(document.createElement("label"));
    __runtime.classes("mark");
    __runtime.push(document.createElement("input"));
    __runtime.attribute("type", "checkbox");
    __runtime.attribute("checked", this.checkCompleteAll);
    __runtime.pop();
    __runtime.push(document.createElement("span"));
    __runtime.classes("mark");
    __runtime.text("Mark all as complete\n");
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("ul"));
    __runtime.classes("list");
    __runtime.each(this.todos, function() {
      __runtime.push(document.createElement("li"));
      __runtime.push(document.createElement("label"));
      __runtime.push(document.createElement("input"));
      __runtime.attribute("type", "checkbox");
      __runtime.attribute("checked", this.checked);
      __runtime.pop();
      __runtime.push(document.createElement("span"));
      __runtime.classes("item", this["class"]);
      __runtime.text(this.description);
      __runtime.pop();
      __runtime.pop();
      return __runtime.pop();
    });
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("totals");
    __runtime.push(document.createElement("div"));
    __runtime.classes("undone");
    __runtime.push(document.createElement("span"));
    __runtime.classes("count");
    __runtime.text(this.undoneCount);
    __runtime.pop();
    __runtime.text("left\n");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("clear");
    __runtime.attribute("click", this.removeDone);
    __runtime.text("Clear\n");
    __runtime.push(document.createElement("span"));
    __runtime.classes("count");
    __runtime.text(this.doneCount);
    __runtime.pop();
    __runtime.text("items\n");
    __runtime.pop();
    __runtime.pop();
    return __runtime.pop();
  }).call(data);
};
